[package]
name = "flux-auth"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/api", "lib/migration"]
resolver = "2"

[dependencies]
flux-auth-api = { path = "lib/api" }
flux-lib = { git = "https://github.com/thefluxapp/flux-lib.git", branch = "dev" }

anyhow = "1.0.94"
thiserror = "2.0.7"
base64 = "0.22.1"
config = { version = "0.14", default-features = false, features = ["toml"] }
log = "0.4.22"
validator = { version = "0.18.1", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v7"] }
rand = "0.8.5"
random_color = "1.0.0"
url = "2.5.4"
chrono = "0.4.39"
jsonwebtoken = "9.3.0"

axum = "0.7.9"

tokio = { version = "1.42.0", features = ["full"] }

tonic = "0.12.3"
tonic-reflection = "0.12.3"
tonic-health = "0.12.3"

sea-orm = { version = "1.1.2", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }

serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
serde_with = { version = "3.11.0", features = ["base64"] }

mry = "0.10.0"

coset = "0.3.8"
sha2 = "0.10.8"
p256 = "0.13.2"
ecdsa = { version = "0.16.9", features = ["der"] }
