[package]
name = "flux-auth"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/api", "lib/migration"]
resolver = "2"

[dependencies]
flux-auth-api = { path = "lib/api" }

anyhow = "1.0.89"
thiserror = "1.0.64"
base64 = "0.22.1"
config = { version = "0.14", default-features = false, features = ["toml"] }
log = "0.4.22"
validator = { version = "0.18.1", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v7"] }
rand = "0.8.5"
url = "2.5.2"
chrono = "0.4.38"
jsonwebtoken = "9.3.0"

axum = "0.7.7"

tokio = { version = "1.40.0", features = ["full"] }

tonic = "0.12.3"
tonic-reflection = "0.12.3"
tonic-health = "0.12.3"

sea-orm = { version = "1.0.1", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_with = { version = "3.11.0", features = ["base64"] }
